### ISSUE TITLE
error on /leap/train-model { status: 520, statusText: '' }

### ISSUE THREAD

**Issue by kumardeepam** [astriaai/headshots-starter#84]
[POST]

/leap/train-model

Time
November 01 19:36:08.56 GMT+05:30
Request Path
/leap/train-model
Host
picmaker.app
Request ID
fvct9-1698847564533-4f135877464d
Request User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Level
Error

Environment
production
Branch
main
Type
Serverless Function

Function
/leap/train-model
Location
Washington, D.C., USA (iad1)
Runtime
Node.js 18.x

{ status: 520, statusText: '' }

**Comment by schananas** [comment]
Managed to fix it.
Turns out that error message was that API key is not in right format, which is wierd, API is provided by Leap.
Digging their discord channels, I found out you need to click "Try Legacy Dashboard", which I assumed it just older UI version but now, there is whole section there that is missing in default UI, its about training models, and also generating API tokens for traning models. Using this this new API token, from legacy dashboard fixed 520, and 401 error.

Very poor user experience by Leap.
